"""Stable wire reason codes shared by authentication, security, and dispatcher."""

NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
INVALID_USERNAME = "INVALID_USERNAME"
INVALID_PASSWORD = "INVALID_PASSWORD"
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
EMPTY_MESSAGE = "EMPTY_MESSAGE"
INVALID_MESSAGE = "INVALID_MESSAGE"
INVALID_ROOM = "INVALID_ROOM"
# Room creation: the requested name breaks the naming policy.
INVALID_ROOM_NAME = "INVALID_ROOM_NAME"
# Room creation: a room with that name already exists; it is never overwritten.
ROOM_ALREADY_EXISTS = "ROOM_ALREADY_EXISTS"
MESSAGE_TOO_LONG = "MESSAGE_TOO_LONG"
ALREADY_AUTHENTICATED = "ALREADY_AUTHENTICATED"
USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
# Internal compatibility alias; wire responses use USERNAME_ALREADY_EXISTS.
DUPLICATE_USERNAME = USERNAME_ALREADY_EXISTS
INVALID_REQUEST_ID = "INVALID_REQUEST_ID"
UNKNOWN_MESSAGE_TYPE = "UNKNOWN_MESSAGE_TYPE"
DLP_SENSITIVE_CONTENT = "DLP_SENSITIVE_CONTENT"
MALICIOUS_ADDRESS = "MALICIOUS_ADDRESS"
# Server-side failure. The client is told only this; never why.
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
